config/routes.rb
Rails.application.routes.draw do
  # resources :yarns
  # resources :projects

  resources :crocheters do
     resources :projects
  end 	

  resources :project do 
  	 resources :yarn 
  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crocheter.rb
class Crocheter < ApplicationRecord
  has_many :projects
  attr_accessor :project 


# cpcp = Crocheter.includes(:project).find(1)
# => #<Crocheter id: 1, name: "Melissa", description: "Melissa loves to crochet...", image_url: "profilePic.png", created_at: "2020-07-26 21:43:09", updated_at: "2020-07-26 21:43:09">
#  cp.project
# => #<ActiveRecord::Associations::CollectionProxy [#<Project id: 1, pattern: "Mandala", hook_size: "I", status: "Complete", crocheter_id: 1, created_at: "2020-07-26 21:43:09", updated_at: "2020-07-26 21:43:09">, #<Project id: 2, pattern: "Small Sunflower", hook_size: "J", status: "In Progress", crocheter_id: 1, created_at: "2020-07-26 21:43:09", updated_at: "2020-07-26 21:43:09">]>
# irb(main):016:0> cp.project.each do |p|
# irb(main):017:1* puts p
# irb(main):018:1> end
# #<Project:0x00007fff3e6f9628>
# #<Project:0x00007fff3eeb9ed0>
# => [#<Project id: 1, pattern: "Mandala", hook_size: "I", status: "Complete", crocheter_id: 1, created_at: "2020-07-26 21:43:09", updated_at: "2020-07-26 21:43:09">, #<Project id: 2, pattern: "Small Sunflower", hook_size: "J", status: "In Progress", crocheter_id: 1, created_at: "2020-07-26 21:43:09", updated_at: "2020-07-26 21:43:09">]
# irb(main):019:0> 

  def self.crocheter_projects(id)
     crocheter_projects = Crocheter.includes(:project).find(:id)
  end 

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :crocheter
  has_many :yarn
end

app/models/yarn.rb
class Yarn < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crocheters_controller.rb
class CrochetersController < ApplicationController
  before_action :set_crocheter, only: [:show, :edit, :update, :destroy]

  # GET /crocheters
  # GET /crocheters.json
  def index
    # @crocheters = Crocheter.all
    @crocheters = Crocheter.includes(:projects)
  
  # @products = Product.includes(:product_images)
  #                  .where(product_images: { default_image: true )
  #                  .last(5)

     # @cp ||= Crocheter.crocheter_projects(param[:crocheter_id])

  end

  # GET /crocheters/1
  # GET /crocheters/1.json
  # default is empty def 
  def show
    @crocheters = Crocheter.includes(:patterns)
    
  end
 
    # respond_to do |format| 
    #   format.html
    # end 


  # GET /crocheters/new
  def new
    @crocheter = Crocheter.new
  end

  # GET /crocheters/1/edit
  def edit
  end

  # POST /crocheters
  # POST /crocheters.json
  def create
    @crocheter = Crocheter.new(crocheter_params)

    respond_to do |format|
      if @crocheter.save
        format.html { redirect_to @crocheter, notice: 'Crocheter was successfully created.' }
        format.json { render :show, status: :created, location: @crocheter }
      else
        format.html { render :new }
        format.json { render json: @crocheter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crocheters/1
  # PATCH/PUT /crocheters/1.json
  def update
    respond_to do |format|
      if @crocheter.update(crocheter_params)
        format.html { redirect_to @crocheter, notice: 'Crocheter was successfully updated.' }
        format.json { render :show, status: :ok, location: @crocheter }
      else
        format.html { render :edit }
        format.json { render json: @crocheter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crocheters/1
  # DELETE /crocheters/1.json
  def destroy
    @crocheter.destroy
    respond_to do |format|
      format.html { redirect_to crocheters_url, notice: 'Crocheter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crocheter
      @crocheter = Crocheter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crocheter_params
      params.require(:crocheter).permit(:id, :name, :description, :image_url)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:pattern, :hook_size, :status, :crocheter_id)
    end
end

app/controllers/yarns_controller.rb
class YarnsController < ApplicationController
  before_action :set_yarn, only: [:show, :edit, :update, :destroy]

  # GET /yarns
  # GET /yarns.json
  def index
    @yarns = Yarn.all
  end

  # GET /yarns/1
  # GET /yarns/1.json
  def show
  end

  # GET /yarns/new
  def new
    @yarn = Yarn.new
  end

  # GET /yarns/1/edit
  def edit
  end

  # POST /yarns
  # POST /yarns.json
  def create
    @yarn = Yarn.new(yarn_params)

    respond_to do |format|
      if @yarn.save
        format.html { redirect_to @yarn, notice: 'Yarn was successfully created.' }
        format.json { render :show, status: :created, location: @yarn }
      else
        format.html { render :new }
        format.json { render json: @yarn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yarns/1
  # PATCH/PUT /yarns/1.json
  def update
    respond_to do |format|
      if @yarn.update(yarn_params)
        format.html { redirect_to @yarn, notice: 'Yarn was successfully updated.' }
        format.json { render :show, status: :ok, location: @yarn }
      else
        format.html { render :edit }
        format.json { render json: @yarn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yarns/1
  # DELETE /yarns/1.json
  def destroy
    @yarn.destroy
    respond_to do |format|
      format.html { redirect_to yarns_url, notice: 'Yarn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yarn
      @yarn = Yarn.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def yarn_params
      params.require(:yarn).permit(:brand, :color, :dye_lot, :quantity, :purchased_at, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crocheters_helper.rb
module CrochetersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/yarns_helper.rb
module YarnsHelper
end

app/views/crocheters/_form.html.erb
<%= form_with(model: crocheter, local: true) do |form| %>
  <% if crocheter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crocheter.errors.count, "error") %> prohibited this crocheter from being saved:</h2>

      <ul>
        <% crocheter.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crocheters/edit.html.erb
<h1>Editing Crocheter</h1>

<%= render 'form', crocheter: @crocheter %>

<%= link_to 'Show', @crocheter %> |
<%= link_to 'Back', crocheters_path %>

app/views/crocheters/index.html.erb
<p id="notice"><%= notice %></p>

<div id="bannerimage"></div>
<h1>Crocheter Profiles</h1>

<table>
  <thead>
    <tr>
      <!-- <th>Id</th> -->
      <!-- <th>Name</th> -->
      <!-- <th>Description</th> -->
      <!-- <th>Image url</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crocheters.each do |crocheter| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="image">
          <%= image_tag(crocheter.image_url, class: 'list_image') %>
        </td>

        <td class="description">
          <h2><%= crocheter.name %></h2>

          <p>
            <%= truncate(strip_tags(crocheter.description),
                         length: 80) %>
          </p>

        </td>
        <!-- <td><%= crocheter.id %></td> -->
        <td>
          <% crocheter.projects.each do |p| %>
             <h4><%= link_to p.pattern, crocheter_project_url(crocheter,p)%></h4>
          <% end %> 
        </td>

        <td class="actions">
          <ul>
            <li><%= link_to 'Show', crocheter %></li>
            <li><%= link_to 'Edit', edit_crocheter_path(crocheter) %></li>
            <li>
              <%= link_to 'Destroy',
                           crocheter, 
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %>
            </li>
          </ul>
        </td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crocheter', new_crocheter_path %>

app/views/crocheters/new.html.erb
<h1>New Crocheter</h1>

<%= render 'form', crocheter: @crocheter %>

<%= link_to 'Back', crocheters_path %>

app/views/crocheters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @crocheter.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @crocheter.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @crocheter.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @crocheter.image_url %>
</p>


<%= link_to 'Edit', edit_crocheter_path(@crocheter) %> |
<%= link_to 'Back', crocheters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleCrochetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class='<%= controller.controller_name %>'>
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pattern %>
    <%= form.text_field :pattern %>
  </div>

  <div class="field">
    <%= form.label :hook_size %>
    <%= form.text_field :hook_size %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :crocheter_id %>
    <%= form.text_field :crocheter_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Pattern</th>
      <th>Hook size</th>
      <th>Status</th>
      <th>Crocheter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.pattern %></td>
        <td><%= project.hook_size %></td>
        <td><%= project.status %></td>
        <td><%= project.crocheter_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', crocheter_projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Pattern</th>
      <th>Hook size</th>
      <th>Status</th>
      <th>Crocheter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.pattern %></td>
        <td><%= project.hook_size %></td>
        <td><%= project.status %></td>
        <td><%= project.crocheter_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pattern:</strong>
  <%= @project.pattern %>
</p>

<p>
  <strong>Hook size:</strong>
  <%= @project.hook_size %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<p>
  <strong>Crocheter:</strong>
  <%= @project.crocheter_id %>
</p>

<%= link_to 'Edit', edit_crocheter_project_path(@project) %> |
<%= link_to 'Back', crocheter_path %>

app/views/yarns/_form.html.erb
<%= form_with(model: yarn, local: true) do |form| %>
  <% if yarn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(yarn.errors.count, "error") %> prohibited this yarn from being saved:</h2>

      <ul>
        <% yarn.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :dye_lot %>
    <%= form.text_field :dye_lot %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/yarns/edit.html.erb
<h1>Editing Yarn</h1>

<%= render 'form', yarn: @yarn %>

<%= link_to 'Show', @yarn %> |
<%= link_to 'Back', yarns_path %>

app/views/yarns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Yarns</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Color</th>
      <th>Dye lot</th>
      <th>Quantity</th>
      <th>Purchased at</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yarns.each do |yarn| %>
      <tr>
        <td><%= yarn.brand %></td>
        <td><%= yarn.color %></td>
        <td><%= yarn.dye_lot %></td>
        <td><%= yarn.quantity %></td>
        <td><%= yarn.weight %></td>
        <td><%= yarn.project_id %></td>
        <td><%= link_to 'Show', yarn %></td>
        <td><%= link_to 'Edit', edit_yarn_path(yarn) %></td>
        <td><%= link_to 'Destroy', yarn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yarn', new_yarn_path %>

app/views/yarns/new.html.erb
<h1>New Yarn</h1>

<%= render 'form', yarn: @yarn %>

<%= link_to 'Back', yarns_path %>

app/views/yarns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @yarn.brand %>
</p>

<p>
  <strong>Color:</strong>
  <%= @yarn.color %>
</p>

<p>
  <strong>Dye lot:</strong>
  <%= @yarn.dye_lot %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @yarn.quantity %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @yarn.purchased_at %>
</p>

<p>
  <strong>Project:</strong>
  <%= @yarn.project_id %>
</p>

<%= link_to 'Edit', edit_yarn_path(@yarn) %> |
<%= link_to 'Back', yarns_path %>